ARCHS = arm64
INSTALL_TARGET_PROCESSES = MobileSlideShow Camera

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = EnableLivePhotosRecording EnableLivePhotosBadge
EnableLivePhotosRecording_FILES = Recording.x
EnableLivePhotosBadge_FILES = Badge.x

include $(THEOS_MAKE_PATH)/tweak.mk
