ARCHS = arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GrabberTime
GrabberTime_FILES = Tweak.x
GrabberTime_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
