ARCHS = arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoClose
NoClose_FILES = Tweak.x
NoClose_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
