ARCHS = arm64
INSTALL_TARGET_PROCESSES = Cydia

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoCydiaAds
NoCydiaAds_FILES = Tweak.x
NoCydiaAds_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
