ARCHS = arm64
INSTALL_TARGET_PROCESSES = MobileSMS

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = BetterLandscapeMessages
BetterLandscapeMessages_FILES = Tweak.x

include $(THEOS_MAKE_PATH)/tweak.mk
