ARCHS = arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NCIfNeeded
NCIfNeeded_FILES = Tweak.x
NCIfNeeded_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
