ARCHS = arm64
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MovaBar
MovaBar_FILES = Tweak.xm
MovaBar_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
